### ISSUE TITLE
nx v18 print-affected

### ISSUE THREAD

**Issue by work933k** [spaceribs/spaceribs#264]
When i run this command in NX v18:
```
npx nx print-affected --target="lint,stylelint,betterer,build,e2e,test,test-storybook" --select="projects"

 NX  Use `nx show projects --affected`, `nx affected --graph -t build` or `nx graph --affected` depending on which best suits your use case. The `print-affected` command will be removed in Nx 19.

 NX   Daemon process terminated and closed the connection
 npx nx print-affected --target="lint,stylelint,betterer,build,e2e,test,test-storybook" --select="projects"
```
The daemon gives an error. In the log i can see that it has got specifically something to do with my "betterer" task.
This is what i see in the log:
```
/root/Dummy/node_modules/nx/src/hasher/native-task-hasher-impl.js:33
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^

TypeError: Cannot convert undefined or null to object
    at NativeTaskHasherImpl.hashTasks (/root/Dummy/node_modules/nx/src/hasher/native-task-hasher-impl.js:33:36)
    at InProcessTaskHasher.hashTasks (/root/Dummy/node_modules/nx/src/hasher/task-hasher.js:53:50)
    at handleHashTasks (/root/Dummy/node_modules/nx/src/daemon/server/handle-hash-tasks.js:30:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (/root/Dummy/node_modules/nx/src/daemon/server/server.js:110:16)
    at async handleMessage (/root/Dummy/node_modules/nx/src/daemon/server/server.js:84:9)
    at async /root/Dummy/node_modules/nx/src/daemon/server/server.js:45:9
```
It's something what didn't use to be an issue on NX v16.

I probably can switch to "nx show projects" as a workaround.

**Comment by spaceribs** [comment]
interesting, I think this and #263 are related so let me look at the caching logic and see if I can figure out a resolution here...

**Comment by spaceribs** [comment]
You can track my progress on setting up a [better hasher for this job here](https://discord.com/channels/1143497901675401286/1229784588591562932), for now I'm going to push to remove the hasher.ts file entirely
